In [1]:
import pandas as pd

In [2]:
companies_info = pd.read_csv('companies_information.csv')

In [4]:
#companies_info

In [7]:
industries_info = pd.read_csv('industries_information.csv')

In [9]:
#industries_info

In [12]:
mergedData = pd.merge(companies_info, industries_info, on = 'IndustryId', how = 'left')

In [ ]:
#includes all the rows from the left DataFrame that have corresponding key = `industryId', in the right DataFrame to merge the data

In [26]:
mergedData

,Ticker,SimFinId,Company Name,IndustryId,Sector,Industry
0,AAON,919501,AAON INC,100001.0,Industrials,Industrial Products
1,ACCO,120923,ACCO BRANDS Corp,100001.0,Industrials,Industrial Products
2,ADES,619745,"Advanced Emissions Solutions, Inc.",100001.0,Industrials,Industrial Products
3,AIMC,773555,Altra Industrial Motion Corp.,100001.0,Industrials,Industrial Products
4,ALOT,995248,"AstroNova, Inc.",100001.0,Industrials,Industrial Products
...,...,...,...,...,...,...
3117,XING,663216,China Xingbang Industry Group Inc.,NaN,NaN,NaN
3118,XLGROUP,903527,XL GROUP LTD,NaN,NaN,NaN
3119,XLO,1872674,"Xilio Therapeutics, Inc.",NaN,NaN,NaN
3120,YITD,660011,"Yinhang Internet Technologies Development, Inc.",NaN,NaN,NaN
3121,ZINCQ,287827,Horsehead Holding Corp,NaN,NaN,NaN

In [16]:
mergedData = pd.merge(companies_info, industries_info, on = 'IndustryId', how = 'inner')

In [ ]:
#includes all rows that have corresponding matching key = IndustryId, in both DataFrames

In [27]:
mergedData

,Ticker,SimFinId,Company Name,IndustryId,Sector,Industry
0,AAON,919501,AAON INC,100001.0,Industrials,Industrial Products
1,ACCO,120923,ACCO BRANDS Corp,100001.0,Industrials,Industrial Products
2,ADES,619745,"Advanced Emissions Solutions, Inc.",100001.0,Industrials,Industrial Products
3,AIMC,773555,Altra Industrial Motion Corp.,100001.0,Industrials,Industrial Products
4,ALOT,995248,"AstroNova, Inc.",100001.0,Industrials,Industrial Products
...,...,...,...,...,...,...
3117,XING,663216,China Xingbang Industry Group Inc.,NaN,NaN,NaN
3118,XLGROUP,903527,XL GROUP LTD,NaN,NaN,NaN
3119,XLO,1872674,"Xilio Therapeutics, Inc.",NaN,NaN,NaN
3120,YITD,660011,"Yinhang Internet Technologies Development, Inc.",NaN,NaN,NaN
3121,ZINCQ,287827,Horsehead Holding Corp,NaN,NaN,NaN

In [21]:
mergedData = pd.merge(companies_info, industries_info, on = 'IndustryId', how = 'outer')

In [ ]:
#includes all the rows from each merging DataFrame and adds a NAN for missing values.

In [28]:
mergedData

,Ticker,SimFinId,Company Name,IndustryId,Sector,Industry
0,AAON,919501,AAON INC,100001.0,Industrials,Industrial Products
1,ACCO,120923,ACCO BRANDS Corp,100001.0,Industrials,Industrial Products
2,ADES,619745,"Advanced Emissions Solutions, Inc.",100001.0,Industrials,Industrial Products
3,AIMC,773555,Altra Industrial Motion Corp.,100001.0,Industrials,Industrial Products
4,ALOT,995248,"AstroNova, Inc.",100001.0,Industrials,Industrial Products
...,...,...,...,...,...,...
3117,XING,663216,China Xingbang Industry Group Inc.,NaN,NaN,NaN
3118,XLGROUP,903527,XL GROUP LTD,NaN,NaN,NaN
3119,XLO,1872674,"Xilio Therapeutics, Inc.",NaN,NaN,NaN
3120,YITD,660011,"Yinhang Internet Technologies Development, Inc.",NaN,NaN,NaN
3121,ZINCQ,287827,Horsehead Holding Corp,NaN,NaN,NaN