In [1]:
import pandas as pd

In [2]:
companies_df = pd.read_csv('companies_information.csv')

In [12]:
industries_df = pd.read_csv('industries_information.csv')

In [13]:
balance_df = pd.read_csv('balance_sheet.csv')

In [14]:
balance_df = balance_df.drop(columns=['Report Date',
                                      'Currency',
                                     'Publish Date',
                                     'Restated Date',
                                     'Shares (Basic)',
                                     'Shares (Diluted)'])

In [15]:
cashflow_df = pd.read_csv('cashflow_statement.csv')

In [16]:
print(cashflow_df.columns.tolist())

['Ticker', 'Report Date', 'SimFinId', 'Currency', 'Fiscal Year', 'Fiscal Period', 'Publish Date', 'Restated Date', 'Shares (Basic)', 'Shares (Diluted)', 'Net Income/Starting Line', 'Depreciation & Amortization', 'Non-Cash Items', 'Change in Working Capital', 'Change in Accounts Receivable', 'Change in Inventories', 'Change in Accounts Payable', 'Change in Other', 'Net Cash from Operating Activities', 'Change in Fixed Assets & Intangibles', 'Net Change in Long Term Investment', 'Net Cash from Acquisitions & Divestitures', 'Net Cash from Investing Activities', 'Dividends Paid', 'Cash from (Repayment of) Debt', 'Cash from (Repurchase of) Equity', 'Net Cash from Financing Activities', 'Net Change in Cash']

In [17]:
cashflow_df = cashflow_df.drop(columns=['Report Date',
                                        'Currency',
                                        'Publish Date',
                                        'Restated Date',
                                        'Shares (Basic)',
                                        'Shares (Diluted)',
                                        'Depreciation & Amortization'])

In [18]:
income_df = pd.read_csv('income_statement.csv')

In [19]:
eps_df = pd.read_csv('eps_df.csv')

In [20]:
merge_df = companies_df.merge(industries_df, on='IndustryId', how='left')\
                       .merge(income_df, on=['Ticker', 'SimFinId'], how='left')\
                       .merge(balance_df, on=['Ticker', 'SimFinId', 'Fiscal Year', 'Fiscal Period'], how='left')\
                       .merge(cashflow_df, on=['Ticker', 'SimFinId', 'Fiscal Year', 'Fiscal Period'], how='left')\
                       .merge(eps_df, on=['Ticker', 'Fiscal Year', 'Fiscal Period'], how='left')

In [21]:
length = len(merge_df.columns)

In [23]:
amazon_df = merge_df[merge_df['Ticker']=='AMZN'].reset_index(drop=True)

In [24]:
amazon_df

,Ticker,SimFinId,Company Name,IndustryId,Sector,Industry,Report Date,Currency,Fiscal Year,Fiscal Period,...,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash,"Earnings Per Share, Basic"
0,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,12/31/2016,USD,2016.0,Q4,...,-2.006000e+09,-1.805000e+09,-3.000000e+06,-3.814000e+09,NaN,-5.680000e+08,NaN,-5.680000e+08,5.993000e+09,0.07835
1,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,3/31/2017,USD,2017.0,Q1,...,-1.861000e+09,5.560000e+08,-4.500000e+07,-1.350000e+09,NaN,-8.880000e+08,NaN,-8.880000e+08,-3.633000e+09,0.07589
2,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,6/30/2017,USD,2017.0,Q2,...,-2.501000e+09,-2.140000e+09,-6.330000e+08,-5.274000e+09,NaN,-1.275000e+09,NaN,-1.275000e+09,-2.450000e+09,0.02056
3,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,9/30/2017,USD,2017.0,Q3,...,-2.660000e+09,-2.606000e+09,-1.321300e+10,-1.847900e+10,NaN,1.466200e+10,NaN,1.466200e+10,1.090000e+08,0.02651
4,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,12/31/2017,USD,2017.0,Q4,...,-3.036000e+09,1.136000e+09,-8.100000e+07,-1.981000e+09,NaN,-2.571000e+09,NaN,-2.571000e+09,7.896000e+09,0.19224
5,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,3/31/2018,USD,2018.0,Q1,...,-2.727000e+09,2.207000e+09,-1.300000e+07,-5.330000e+08,NaN,-2.164000e+09,NaN,-2.164000e+09,-4.240000e+09,0.16829
6,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,6/30/2018,USD,2018.0,Q2,...,-2.949000e+09,1.123000e+09,-8.660000e+08,-2.692000e+09,NaN,-1.392000e+09,NaN,-1.392000e+09,2.920000e+09,0.26070
7,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,9/30/2018,USD,2018.0,Q3,...,-2.527000e+09,-2.069000e+09,-9.760000e+08,-5.572000e+09,NaN,-2.369000e+09,NaN,-2.369000e+09,4.960000e+08,0.29539
8,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,12/31/2018,USD,2018.0,Q4,...,-3.120000e+09,-1.210000e+08,-3.310000e+08,-3.572000e+09,NaN,-1.761000e+09,NaN,-1.761000e+09,1.114100e+10,0.30888
9,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,3/31/2019,USD,2019.0,Q1,...,-2.721000e+09,-4.233000e+09,-1.169000e+09,-8.123000e+09,NaN,-2.377000e+09,NaN,-2.377000e+09,-8.666000e+09,0.36263
10,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,6/30/2019,USD,2019.0,Q2,...,-2.643000e+09,-4.790000e+09,-1.160000e+08,-7.549000e+09,NaN,-2.158000e+09,NaN,-2.158000e+09,-5.420000e+08,0.26623
11,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,9/30/2019,USD,2019.0,Q3,...,-3.385000e+09,-1.289000e+09,-3.990000e+08,-5.073000e+09,NaN,-1.960000e+09,NaN,-1.960000e+09,5.890000e+08,0.21556
12,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,12/31/2019,USD,2019.0,Q4,...,-3.940000e+09,1.181000e+09,-7.770000e+08,-3.536000e+09,NaN,-3.571000e+09,NaN,-3.571000e+09,1.285600e+10,0.32877
13,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,3/31/2020,USD,2020.0,Q1,...,-5.428000e+09,-3.375000e+09,-9.100000e+07,-8.894000e+09,NaN,-2.591000e+09,NaN,-2.591000e+09,-8.905000e+09,0.25452
14,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,6/30/2020,USD,2020.0,Q2,...,-6.614000e+09,-1.107100e+10,-1.190000e+08,-1.780400e+10,NaN,7.408000e+09,NaN,7.408000e+09,1.033700e+10,0.52430
15,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,9/30/2020,USD,2020.0,Q3,...,-9.808000e+09,-4.333000e+09,-1.735000e+09,-1.587600e+10,NaN,-4.105000e+09,NaN,-4.105000e+09,-7.640000e+09,0.63058
16,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,12/31/2020,USD,2020.0,Q4,...,-1.319400e+10,-3.463000e+09,-3.800000e+08,-1.703700e+10,NaN,-1.816000e+09,NaN,-1.816000e+09,1.217500e+10,0.72220
17,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,3/31/2021,USD,2021.0,Q1,...,-1.118700e+10,3.151000e+09,-6.300000e+08,-8.666000e+09,NaN,-3.476000e+09,NaN,-3.476000e+09,-8.222000e+09,0.80427
18,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,6/30/2021,USD,2021.0,Q2,...,-1.298800e+10,-8.772000e+09,-3.200000e+08,-2.208000e+10,NaN,1.564300e+10,NaN,1.564300e+10,6.512000e+09,0.77163
19,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,9/30/2021,USD,2021.0,Q3,...,-1.574800e+10,5.770000e+08,-6.540000e+08,-1.482800e+10,NaN,-2.776000e+09,NaN,-2.776000e+09,-1.049000e+10,0.31248

In [27]:
fiscal_encoded = pd.get_dummies(amazon_df['Fiscal Period'], dtype=int)

In [28]:
fiscal_encoded

    Q1  Q2  Q3  Q4
0    0   0   0   1
1    1   0   0   0
2    0   1   0   0
3    0   0   1   0
4    0   0   0   1
5    1   0   0   0
6    0   1   0   0
7    0   0   1   0
8    0   0   0   1
9    1   0   0   0
10   0   1   0   0
11   0   0   1   0
12   0   0   0   1
13   1   0   0   0
14   0   1   0   0
15   0   0   1   0
16   0   0   0   1
17   1   0   0   0
18   0   1   0   0
19   0   0   1   0

In [29]:
amazon_df = amazon_df.drop('Fiscal Period', axis = 1)

In [30]:
amazon_df = pd.concat([amazon_df, fiscal_encoded], axis = 1)

In [31]:
amazon_df

,Ticker,SimFinId,Company Name,IndustryId,Sector,Industry,Report Date,Currency,Fiscal Year,Publish Date,...,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash,"Earnings Per Share, Basic",Q1,Q2,Q3,Q4
0,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,12/31/2016,USD,2016.0,2/10/2017,...,NaN,-5.680000e+08,NaN,-5.680000e+08,5.993000e+09,0.07835,0,0,0,1
1,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,3/31/2017,USD,2017.0,4/28/2017,...,NaN,-8.880000e+08,NaN,-8.880000e+08,-3.633000e+09,0.07589,1,0,0,0
2,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,6/30/2017,USD,2017.0,7/28/2017,...,NaN,-1.275000e+09,NaN,-1.275000e+09,-2.450000e+09,0.02056,0,1,0,0
3,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,9/30/2017,USD,2017.0,10/27/2017,...,NaN,1.466200e+10,NaN,1.466200e+10,1.090000e+08,0.02651,0,0,1,0
4,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,12/31/2017,USD,2017.0,2/2/2018,...,NaN,-2.571000e+09,NaN,-2.571000e+09,7.896000e+09,0.19224,0,0,0,1
5,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,3/31/2018,USD,2018.0,4/27/2018,...,NaN,-2.164000e+09,NaN,-2.164000e+09,-4.240000e+09,0.16829,1,0,0,0
6,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,6/30/2018,USD,2018.0,7/27/2018,...,NaN,-1.392000e+09,NaN,-1.392000e+09,2.920000e+09,0.26070,0,1,0,0
7,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,9/30/2018,USD,2018.0,10/26/2018,...,NaN,-2.369000e+09,NaN,-2.369000e+09,4.960000e+08,0.29539,0,0,1,0
8,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,12/31/2018,USD,2018.0,2/1/2019,...,NaN,-1.761000e+09,NaN,-1.761000e+09,1.114100e+10,0.30888,0,0,0,1
9,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,3/31/2019,USD,2019.0,4/26/2019,...,NaN,-2.377000e+09,NaN,-2.377000e+09,-8.666000e+09,0.36263,1,0,0,0
10,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,6/30/2019,USD,2019.0,7/26/2019,...,NaN,-2.158000e+09,NaN,-2.158000e+09,-5.420000e+08,0.26623,0,1,0,0
11,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,9/30/2019,USD,2019.0,10/25/2019,...,NaN,-1.960000e+09,NaN,-1.960000e+09,5.890000e+08,0.21556,0,0,1,0
12,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,12/31/2019,USD,2019.0,1/31/2020,...,NaN,-3.571000e+09,NaN,-3.571000e+09,1.285600e+10,0.32877,0,0,0,1
13,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,3/31/2020,USD,2020.0,5/1/2020,...,NaN,-2.591000e+09,NaN,-2.591000e+09,-8.905000e+09,0.25452,1,0,0,0
14,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,6/30/2020,USD,2020.0,7/31/2020,...,NaN,7.408000e+09,NaN,7.408000e+09,1.033700e+10,0.52430,0,1,0,0
15,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,9/30/2020,USD,2020.0,10/30/2020,...,NaN,-4.105000e+09,NaN,-4.105000e+09,-7.640000e+09,0.63058,0,0,1,0
16,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,12/31/2020,USD,2020.0,2/3/2021,...,NaN,-1.816000e+09,NaN,-1.816000e+09,1.217500e+10,0.72220,0,0,0,1
17,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,3/31/2021,USD,2021.0,4/30/2021,...,NaN,-3.476000e+09,NaN,-3.476000e+09,-8.222000e+09,0.80427,1,0,0,0
18,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,6/30/2021,USD,2021.0,7/30/2021,...,NaN,1.564300e+10,NaN,1.564300e+10,6.512000e+09,0.77163,0,1,0,0
19,AMZN,62747,AMAZON COM INC,103002.0,Consumer Cyclical,Retail - Apparel & Specialty,9/30/2021,USD,2021.0,10/29/2021,...,NaN,-2.776000e+09,NaN,-2.776000e+09,-1.049000e+10,0.31248,0,0,1,0