In [1]:
!pip install simfin

Collecting simfin
  Downloading simfin-1.0.1-py3-none-any.whl.metadata (637 bytes)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (from simfin) (2.2.3)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (from simfin) (2.1.3)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.13/site-packages (from simfin) (2.32.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas->simfin) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas->simfin) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas->simfin) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas->simfin) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests->simfin) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests->simfin) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests->simfin) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests->simfin) (2025.8.3)
Downloading simfin-1.0.1-py3-none-any.whl (61 kB)
Installing collected packages: simfin
Successfully installed simfin-1.0.1

In [2]:
import simfin as sf
import pandas as pd

In [5]:
sf.set_api_key('e544178f-6750-4e6a-bbca-1de6df86f3a2')

In [6]:
sf.set_data_dir('/Users/adeenabilal/Documents/pythonCoursera/JupyterNotebook')

In [10]:
cashFlow_df = sf.load_cashflow(variant = 'annual', market = 'us').reset_index()

Dataset "us-cashflow-annual" not on disk.
- Downloading ... 100.0%
- Extracting zip-file ... Done!
Done!ding from disk ...

/opt/anaconda3/lib/python3.13/site-packages/simfin/load.py:154: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  df = pd.read_csv(path, sep=';', header=0,

In [11]:
cashFlow_df

,Ticker,Report Date,SimFinId,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),...,Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash
0,A,2019-10-31,45846,USD,2019,FY,2019-12-19,2021-12-17,314000000.0,318000000.0,...,1.021000e+09,-155000000.0,NaN,-1.408000e+09,-1.590000e+09,-206000000.0,600000000.0,-6.690000e+08,-2.990000e+08,-866000000
1,A,2020-10-31,45846,USD,2020,FY,2020-12-18,2022-12-21,309000000.0,312000000.0,...,9.210000e+08,-118000000.0,NaN,NaN,-1.470000e+08,-222000000.0,-45000000.0,-4.090000e+08,-7.170000e+08,59000000
2,A,2021-10-31,45846,USD,2021,FY,2021-12-17,2023-12-20,305000000.0,307000000.0,...,1.485000e+09,-187000000.0,12000000.0,-5.470000e+08,-7.490000e+08,-236000000.0,356000000.0,-7.330000e+08,-6.960000e+08,43000000
3,A,2022-10-31,45846,USD,2022,FY,2022-12-21,2024-12-20,304000000.0,307000000.0,...,1.312000e+09,-291000000.0,9000000.0,-5.200000e+07,-3.340000e+08,-250000000.0,22000000.0,-1.081000e+09,-1.376000e+09,-434000000
4,A,2023-10-31,45846,USD,2023,FY,2023-12-20,2024-12-20,294000000.0,296000000.0,...,1.772000e+09,-298000000.0,-3000000.0,-1.000000e+06,-3.020000e+08,-265000000.0,-43000000.0,-5.080000e+08,-9.380000e+08,537000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17729,ZYXI,2022-12-31,171401,USD,2022,FY,2023-03-14,2024-03-12,38467000.0,39127000.0,...,1.374600e+07,-418000.0,NaN,NaN,-4.180000e+05,-3613000.0,-5451000.0,-2.638000e+07,-3.579600e+07,-22468000
17730,ZYXI,2023-12-31,171401,USD,2023,FY,2024-03-12,2025-03-11,35555000.0,36142000.0,...,1.775600e+07,-1156000.0,NaN,NaN,-9.660000e+05,-3000.0,46223000.0,-3.783800e+07,7.645000e+06,24435000
17731,NaN,2021-12-31,18728220,USD,2021,FY,2022-04-18,2024-04-08,8987798.0,8987798.0,...,1.111756e+07,-1347240.0,NaN,NaN,-5.571129e+06,NaN,-774927.0,3.118309e+07,2.554102e+07,30767804
17732,NaN,2022-12-31,18728220,USD,2022,FY,2023-04-18,2025-04-11,10648900.0,10661521.0,...,-4.085683e+07,-9930106.0,NaN,NaN,-4.931050e+06,NaN,2519301.0,2.140515e+07,2.392445e+07,-21695083
17733,NaN,2023-12-31,18728220,USD,2023,FY,2024-04-08,2025-04-11,5888507.0,5888507.0,...,-1.886632e+07,-14909825.0,NaN,NaN,-1.490982e+07,NaN,17911307.0,1.029055e+07,2.820186e+07,-5551701

In [12]:
cashFlow_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17734 entries, 0 to 17733
Data columns (total 28 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Ticker                                     17731 non-null  object
 1   Report Date                                17734 non-null  datetime64[ns]
 2   SimFinId                                   17734 non-null  int64
 3   Currency                                   17734 non-null  object
 4   Fiscal Year                                17734 non-null  int64
 5   Fiscal Period                              17734 non-null  object
 6   Publish Date                               17734 non-null  datetime64[ns]
 7   Restated Date                              17734 non-null  datetime64[ns]
 8   Shares (Basic)                             17561 non-null  float64
 9   Shares (Diluted)                           17432 non-null  float64
 10  Net Income/Starting Line                   17584 non-null  float64
 11  Depreciation & Amortization                16806 non-null  float64
 12  Non-Cash Items                             17565 non-null  float64
 13  Change in Working Capital                  17639 non-null  float64
 14  Change in Accounts Receivable              259 non-null    float64
 15  Change in Inventories                      190 non-null    float64
 16  Change in Accounts Payable                 214 non-null    float64
 17  Change in Other                            318 non-null    float64
 18  Net Cash from Operating Activities         17726 non-null  float64
 19  Change in Fixed Assets & Intangibles       16385 non-null  float64
 20  Net Change in Long Term Investment         6268 non-null   float64
 21  Net Cash from Acquisitions & Divestitures  7172 non-null   float64
 22  Net Cash from Investing Activities         17269 non-null  float64
 23  Dividends Paid                             6237 non-null   float64
 24  Cash from (Repayment of) Debt              14082 non-null  float64
 25  Cash from (Repurchase of) Equity           14099 non-null  float64
 26  Net Cash from Financing Activities         17452 non-null  float64
 27  Net Change in Cash                         17734 non-null  int64
dtypes: datetime64[ns](3), float64(19), int64(3), object(3)
memory usage: 3.8+ MB

In [13]:
print('Memory usage for Annual cash flow Panda Data frame is 3.8+ MB')

Memory usage for Annual cash flow Panda Data frame is 3.8+ MB